### ISSUE TITLE
Get Neatline Text to work with Omeka S

### ISSUE THREAD

**Issue by amandavisconti** [amandavisconti/NeatlineText#7]
Install and list errors/issues; not sure whether this is the point where I move to scholarslab/NeatlineText work, or if updating to work with Omeka S will be fairly simple and the bulk of my work will be after (improving the plugin). Famous last words...

**Comment by amandavisconti** [comment]
Need to look at how Beth's docker-compose.yml lets her point to a custom plugin folder, to be able to point my install of Omeka S to the Neatline Text plugin. Note how she's added folders under "volumes" (I'd already tried this, so I should figure out why how I added it didn't work; remember Neatline Text plugin probably will not _work_ with Omeka S, so I'm only looking to get Omeka S registering that it is a plugin available to enable):

```
version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - project_data:/var/lib/mysql
      - ./project_data/omeka.sql:/docker-entrypoint-initdb.d/omeka.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: omeka
      MYSQL_DATABASE: omeka
      MYSQL_USER: omeka
      MYSQL_PASSWORD: omeka

  omeka:
    depends_on:
      - db
    image: jeremyboggs/omeka
    volumes:
      - ./omeka_plugins/plugin-Coins:/var/www/html/plugins/Coins
      - ./omeka_plugins/plugin-Contribution:/var/www/html/plugins/Contribution
      - ./omeka_plugins/plugin-DerivativeImages:/var/www/html/plugins/DerivativeImages
      - ./omeka_plugins/plugin-DublinCoreExtended:/var/www/html/plugins/DublinCoreExtended
      - ./omeka_plugins/omeka-plugin-ElementTypes:/var/www/html/plugins/ElementTypes
      - ./omeka_plugins/plugin-ExhibitBuilder:/var/www/html/plugins/ExhibitBuilder
      - ./omeka_plugins/plugin-GuestUser:/var/www/html/plugins/GuestUser
      - ./omeka_plugins/plugin-SimplePages:/var/www/html/plugins/SimplePages
      - ./omeka_plugins/plugin-SimpleVocab:/var/www/html/plugins/SimpleVocab
      - ./omeka_plugins/plugin-SearchByMetadata:/var/www/html/plugins/SearchByMetadata
      - ./omeka_themes/cville_rally_theme:/var/www/html/themes/cville_rally_theme
      - ./omeka_file_uploads:/var/www/html/files
    ports:
      - "9000:80"
    restart: always
      
volumes:
  project_data:
  omeka_plugins:
  omeka_themes:
  omeka_file_uploads:
```
